# Generated by Django 3.1.2 on 2021-11-30 00:03

import django.contrib.auth.models
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.CharField(default='None yet!', max_length=600),
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_needed',
            field=models.CharField(default=main_app.models.Skill, max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_teachable',
            field=models.CharField(default=main_app.models.Skill, max_length=1000),
        ),
    ]
