# Generated by Django 3.1.2 on 2021-12-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211130_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='about',
        ),
        migrations.RemoveField(
            model_name='project',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_teachable',
        ),
    ]
