# Generated by Django 3.1.2 on 2021-12-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20211201_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default="I'm an artist!", max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Here', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_current',
            field=models.ManyToManyField(related_name='users_have', to='main_app.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills_learn',
            field=models.ManyToManyField(related_name='users_learn', to='main_app.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.CharField(default="It's so cool", max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='projects_collab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='There', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills_needed',
            field=models.ManyToManyField(related_name='projects_required', to='main_app.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_teachable',
            field=models.ManyToManyField(related_name='projects_teach', to='main_app.Skill'),
        ),
    ]
